/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.slf4j.Logger
import org.slf4j.LoggerFactory
import software.amazon.awssdk.http.apache.ApacheHttpClient
import software.amazon.awssdk.services.dynamodb.DynamoDbClient
import java.net.URI

class App {
    private val ddb = DynamoDbClient.builder()
        .endpointOverride(URI.create("http://localhost:8000"))
        .httpClientBuilder(ApacheHttpClient.builder())
        .build()

    fun getTables(): List<String> = ddb.listTables().tableNames()
}

val logger: Logger = LoggerFactory.getLogger(App::class.java)
fun main() {
    val tables = App().getTables()
    logger.info("tables (${tables.size}): " + tables.joinToString(","))
}